### ISSUE TITLE
Define default values for variables

### ISSUE THREAD

**Issue by SampaioLeal** [SampaioLeal/butiko#1]
Make the above use case supported by the tool

```yaml
spec:
  template:
    spec:
      containers:
        - name: main
          imagePullPolicy: "{{IMAGE_PULL_POLICY:Always}}"
```
